- name: Install unbound
  apt: name={{ item }} state=installed update_cache=true
  with_items:
    - unbound
    - unbound-host

- name: Download the list of Root DNS Server
  get_url:
    url: https://www.internic.net/domain/named.cache
    dest: /var/lib/unbound/root.hints
    owner: unbound
    group: unbound

- name: Generate unbound config
  template:
    src: "templates/unbound.conf"
    dest: "/etc/unbound/unbound.conf"

- name: Enable and start unbound service
  systemd:
    name: unbound
    enabled: yes
    state: started

- name: Set var/lib/unbound ownership
  file:
    path: /var/lib/unbound
    owner: unbound
    group: unbound
    recurse: yes