#The server keys will be 0.private and 0.public. The client keys will start from 1 onwards.
#Note the number of clients is declared in "defaults/main.yml".

- name: Generate private and public keys for the client and server
  shell: umask 077; wg genkey | tee {{ item }}.private | wg pubkey > {{ item }}.public
  register: key_files
  with_sequence: start=0 end={{ clients }}

- name: Register private key file contents
  shell: cat {{ item }}.private
  register: private_key_files
  with_sequence: start=0 end={{ clients }}

- name: Register public key file contents
  shell: cat {{ item }}.public
  register: public_key_files
  with_sequence: start=0 end={{ clients }}

- name: Generate server config
  template:
    src: "templates/server.conf"
    dest: "/etc/wireguard/wg0.conf"
    owner: root
    group: root
    mode: 0600

- name: Generate client configs
  template:
    src: "templates/client.conf"
    dest: "~/client_{{ item }}.conf"
    owner: root
    group: root
    mode: 0600
  with_sequence: start=1 end={{ clients }}

- name: Generate template for additional clients in future
  template:
    src: "templates/add_client.conf"
    dest: "~/new_client.conf"
    owner: root
    group: root
    mode: 0600

- name:  Download the template for additional clients in future
  fetch: 
    src: "~/new_client.conf"
    dest: "wireguard_role/templates/new_client.conf"
    flat: yes

- name: Enable wireguard interface
  systemd:
    name: wg-quick@wg0
    enabled: yes
    state: started

- name: Register the clients on the vpn server
  shell: wg set wg0 peer {{ public_key_files.results[item|int].stdout }} allowed-ips {{ vpn_network }}.{{item|int + 1}}/32
  with_sequence: start=1 end={{ clients }}